name: APK Modification Pipeline

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 PyGithub python-telegram-bot
        
    - name: Install Android tools
      run: |
        sudo apt-get update
        sudo apt-get install -y apksigner zipalign
        
    - name: Install apktool
      run: |
        wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.7.0.jar -O apktool.jar
        wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O apktool
        chmod +x apktool
        sudo mv apktool apktool.jar /usr/local/bin/
        
    - name: Create keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks
        
    - name: Create config file
      run: |
        cat > config.ini << EOL
        [APK]
        name = Instagram
        package = com.instagram.android
        source_url = https://apkcombo.com/instagram/com.instagram.android/download/phone-64bit
        
        [GitHub]
        token = ${{ secrets.GITHUB_TOKEN }}
        repo = ${{ github.repository }}
        
        [Telegram]
        bot_token = ${{ secrets.TELEGRAM_BOT_TOKEN }}
        chat_id = ${{ secrets.TELEGRAM_CHAT_ID }}
        
        [Signing]
        keystore_path = keystore.jks
        keystore_password = ${{ secrets.KEYSTORE_PASSWORD }}
        key_alias = ${{ secrets.KEY_ALIAS }}
        key_password = ${{ secrets.KEY_PASSWORD }}
        
        [Website]
        path = website/index.html
        template_path = website_template.html
        EOL
        
    - name: Run APK pipeline
      run: python apk_pipeline.py
      
    - name: Deploy website to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: website
