name: Auto Notify Telegram

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          CHANGELOG=$(echo "${{ github.event.release.body }}" | sed ':a;N;$!ba;s/\r//g; s/\n/%0A/g')
          
          APK_URL=$(jq -r '.release.assets[] | select(.name | endswith(".apk")) | .browser_download_url' "$GITHUB_EVENT_PATH")

          MESSAGE="<b>Instella ${TAG_NAME}</b>%0A%0A<b>📰 Changelog:-</b>%0A${CHANGELOG}"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d message_thread_id="${TELEGRAM_TOPIC_ID}" \
            -d parse_mode="HTML" \
            -d text="$MESSAGE" \
            -d reply_markup="{\"inline_keyboard\":[[{\"text\":\"Download ${TAG_NAME}\",\"url\":\"${APK_URL}\"}]]}"
