name: Notify Admin - Release Alert

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify_admin:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "VERSION=${{ github.event.release.tag_name || 'Manual' }}" >> $GITHUB_ENV
          echo "RELEASE_URL=${{ github.event.release.html_url || 'https://github.com/${{ github.repository }}/releases' }}" >> $GITHUB_ENV
          echo "IS_PRERELEASE=${{ github.event.release.prerelease || 'false' }}" >> $GITHUB_ENV
        shell: bash

      - name: Send Telegram Alert
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_GROUP_ID }}
          VERSION: ${{ env.VERSION }}
          RELEASE_URL: ${{ env.RELEASE_URL }}
          IS_PRERELEASE: ${{ env.IS_PRERELEASE }}
        run: |
          MESSAGE="🛠️ *Release Notification!*\n\n📦 Version: *${VERSION}*\n🔗 [View Release on GitHub](${RELEASE_URL})\n\nStatus: $([ \"$IS_PRERELEASE\" = \"true\" ] && echo 'Pre-release for testing' || echo 'Published release')"

          curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="Markdown" \
            -d text="$MESSAGE"
