name: Notify Admin - Pre-release

on:
  release:
    types: [published]

jobs:
  notify_admin:
    if: ${{ github.event.release.prerelease }}  # Only for pre-releases
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Alert
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_GROUP_ID }}
          VERSION: ${{ github.event.release.tag_name }}
          RELEASE_URL: ${{ github.event.release.html_url }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="Markdown" \
            -d text="🛠️ *Pre-release Created!*\n\n📦 Version: *${VERSION}*\n🔗 [View Release on GitHub](${RELEASE_URL})\n\nPlease test before publishing!"
