name: Notify Admin - Release Alert

on:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  notify_admin:
    runs-on: ubuntu-latest
    steps:
      - name: Set release info from GitHub context
        run: |
          echo "VERSION=${{ github.event.release.tag_name || 'Manual' }}" >> $GITHUB_ENV
          echo "IS_DRAFT=${{ github.event.release.draft || 'false' }}" >> $GITHUB_ENV
          echo "IS_PRERELEASE=${{ github.event.release.prerelease || 'false' }}" >> $GITHUB_ENV
          echo "RELEASE_URL=${{ github.event.release.html_url || format('https://github.com/{0}/releases', github.repository) }}" >> $GITHUB_ENV

      - name: Send Telegram Alert
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_ADMIN_GROUP_ID }}
          VERSION: ${{ env.VERSION }}
          RELEASE_URL: ${{ env.RELEASE_URL }}
          IS_DRAFT: ${{ env.IS_DRAFT }}
        run: |
          if [ "$IS_DRAFT" = "true" ]; then
            STATUS="📝 *Draft Release*"
          else
            STATUS="🚀 *Release Published*"
          fi

          TEXT="$STATUS\n\n📦 *Version:* ${VERSION}\n🔗 [View on GitHub](${RELEASE_URL})\n\nPlease test or verify it accordingly."

          curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="Markdown" \
            -d text="$TEXT"
